"""
Render success is not production success — so the render gets listened to.

Directive §21 draws the line and §5 says how to check it: after editing,
**re-transcribe the result** and compare it against what was supposed to come
out. Not because encoders are unreliable — they mostly are not — but because
everything upstream can be individually correct and still produce a cut that
removes the word "pas". The encoder reports success. The file plays. The
sentence now says the opposite of what the speaker said.

That failure is invisible to every check that does not listen to the output. A
duration check passes. A frame check passes. Only re-reading the words catches
it, which is why §5 asks for it specifically and why this module exists.

Two rules keep the verdict honest.

**A verification that could not run is `NOT_VERIFIED`, never a pass.** With no
transcriber on this machine, the honest output is a refusal to certify — the
same shape as `NOT_MEASURABLE` in Darra J's evaluation lab. A pipeline that
reports "verified" because it skipped the verification is worse than one with no
verification at all: it manufactures confidence out of an absence.

**Comparison is mechanical and word-level.** Missing, added and moved words are
computed by sequence alignment, not judged by a model. Asking a model whether
two transcripts mean the same thing would replace a measurement with an opinion,
and the opinion would be generated by the same kind of system that produced the
error.

What this cannot see is stated rather than omitted: a word the transcriber
misheard identically in both passes cancels out, and prosody, tone and delivery
are outside a word sequence entirely.
"""

from __future__ import annotations

import difflib
import unicodedata
from typing import Any, Dict, List, Optional, Sequence

#: Les verdicts. `NOT_VERIFIED` n'est pas un échec : c'est l'absence de
#: vérification, et la confondre avec une réussite fabriquerait de la confiance
#: à partir d'une absence.
CONFORME = "MATCHES_INTENT"
DIVERGENT = "DIVERGED"
NON_VERIFIE = "NOT_VERIFIED"

#: Ce que cette comparaison ne peut pas voir. Nommé, parce qu'une liste de
#: contrôles qui ne montre que le détectable se lit comme complète.
HORS_PORTEE = {
    "identical_mishearing": (
        "Un mot mal entendu **de la même façon** aux deux passes s'annule : la "
        "comparaison porte sur deux transcriptions, pas sur la vérité."
    ),
    "prosody": (
        "Ton, débit, intention. Une suite de mots n'en porte rien, et un "
        "montage peut les casser sans changer un seul mot."
    ),
    "picture": (
        "L'image. Cette vérification écoute ; elle ne regarde pas."
    ),
}


class VerificationRefused(ValueError):
    """Une vérification qu'on ne peut pas conduire telle qu'elle est demandée."""


def _mots(texte: str) -> List[str]:
    """Découpe un texte en mots comparables : sans casse, sans accent, sans ponctuation."""
    decompose = unicodedata.normalize("NFKD", str(texte or ""))
    sans_accent = "".join(c for c in decompose if not unicodedata.combining(c))
    nettoye = "".join(
        c if c.isalnum() or c.isspace() else " " for c in sans_accent.casefold()
    )
    return nettoye.split()


def compare_transcripts(intended: str, final: str) -> Dict[str, Any]:
    """
    Compare ce qui devait sortir à ce qui est sorti, mot à mot.

    Args:
        intended: Le texte que le montage devait produire.
        final: Le texte re-transcrit depuis le rendu.

    Returns:
        Les mots manquants, ajoutés et déplacés, avec le taux de conservation.
        L'alignement est **mécanique** : demander à un modèle si deux
        transcriptions veulent dire la même chose remplacerait une mesure par
        une opinion, produite par le même genre de système que l'erreur.

    Raises:
        VerificationRefused: Si le texte attendu est vide. Comparer à rien
            rendrait « tout est manquant » ou « tout va bien » selon le sens de
            lecture, et aucune des deux n'est une mesure.
    """
    attendus = _mots(intended)
    obtenus = _mots(final)
    if not attendus:
        raise VerificationRefused(
            "Texte attendu vide : la comparaison n'aurait pas de référence, et "
            "rendrait « tout manque » ou « tout va bien » selon le sens de "
            "lecture."
        )

    aligneur = difflib.SequenceMatcher(a=attendus, b=obtenus, autojunk=False)
    manquants: List[Dict[str, Any]] = []
    ajoutes: List[Dict[str, Any]] = []
    conserves = 0

    for operation, a1, a2, b1, b2 in aligneur.get_opcodes():
        if operation == "equal":
            conserves += a2 - a1
        elif operation in ("delete", "replace"):
            manquants.extend(
                {"word": attendus[i], "at_word": i} for i in range(a1, a2)
            )
            if operation == "replace":
                ajoutes.extend(
                    {"word": obtenus[j], "at_word": j} for j in range(b1, b2)
                )
        elif operation == "insert":
            ajoutes.extend(
                {"word": obtenus[j], "at_word": j} for j in range(b1, b2)
            )

    doublons = _doublons(attendus, obtenus)
    return {
        "intended_words": len(attendus),
        "final_words": len(obtenus),
        "kept_words": conserves,
        "retention": round(conserves / len(attendus), 4),
        "missing": manquants,
        "added": ajoutes,
        "duplicated": doublons,
        "identical": conserves == len(attendus) and len(obtenus) == len(attendus),
    }


def _doublons(attendus: Sequence[str], obtenus: Sequence[str]) -> List[Dict[str, Any]]:
    """
    Les mots apparaissant plus souvent dans le rendu que prévu.

    Un mot doublé est le signe d'un extrait collé deux fois — une faute de
    montage que le seul décompte des manquants ne verrait pas.
    """
    from collections import Counter

    prevu, rendu = Counter(attendus), Counter(obtenus)
    return [
        {"word": mot, "expected": prevu[mot], "found": compte}
        for mot, compte in sorted(rendu.items())
        if compte > prevu.get(mot, 0)
    ]


def verify_render(
    intended: str,
    final_transcript: Optional[str] = None,
    tolerance: float = 1.0,
) -> Dict[str, Any]:
    """
    Vérifie qu'un rendu dit bien ce qu'il devait dire.

    Args:
        intended: Le texte attendu, typiquement `edit_plan.intended_transcript`.
        final_transcript: Le texte **re-transcrit depuis le fichier rendu**.
            Absent, aucune vérification n'est prononcée.
        tolerance: Part minimale de mots conservés pour déclarer conforme. Le
            défaut est 1.0 : un montage est censé garder exactement ce qu'il a
            sélectionné, et tolérer une perte par défaut normaliserait la faute
            que ce contrôle cherche.

    Returns:
        Le verdict, les écarts, et — quand la vérification n'a pas pu avoir
        lieu — `NOT_VERIFIED` avec sa raison. Un rendu terminé n'est pas un
        rendu vérifié, et une chaîne qui rapporterait « vérifié » parce qu'elle
        a sauté le contrôle fabriquerait de la confiance à partir d'une absence.
    """
    if final_transcript is None:
        return {
            "verdict": NON_VERIFIE,
            "reason": (
                "Aucune re-transcription du rendu. Le rendu s'est peut-être "
                "terminé sans erreur — cela ne dit rien de ce qu'il contient. "
                "Une coupe qui enlève le mot « pas » produit un fichier qui "
                "s'encode, se lit, et dit le contraire de ce qui a été dit."
            ),
            "out_of_scope": dict(HORS_PORTEE),
        }

    ecarts = compare_transcripts(intended, final_transcript)
    conforme = (
        ecarts["retention"] >= tolerance
        and not ecarts["added"]
        and not ecarts["duplicated"]
    )

    return {
        "verdict": CONFORME if conforme else DIVERGENT,
        "tolerance": tolerance,
        **ecarts,
        "out_of_scope": dict(HORS_PORTEE),
        "reason": (
            "Le rendu dit exactement ce que le plan avait retenu."
            if conforme else
            f"{len(ecarts['missing'])} mot(s) manquant(s), "
            f"{len(ecarts['added'])} ajouté(s), "
            f"{len(ecarts['duplicated'])} dupliqué(s). Un rendu terminé n'est "
            "pas un rendu vérifié."
        ),
    }


def boundary_losses(
    plan: Dict[str, Any], comparison: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Les mots perdus **au bord** d'un extrait — la signature d'une coupe trop courte.

    Args:
        plan: Le plan rendu par `edit_plan.build_plan`.
        comparison: Le résultat de `compare_transcripts`.

    Returns:
        Les pertes situées au premier ou au dernier mot d'un segment. Un mot
        perdu au milieu vient d'autre chose ; un mot perdu au bord vient de la
        coupe, et distinguer les deux dit **quoi corriger**.
    """
    if not comparison.get("missing"):
        return []

    bords = set()
    position = 0
    for segment in plan.get("objects", []):
        longueur = len(segment.words)
        if longueur:
            bords.add(position)
            bords.add(position + longueur - 1)
        position += longueur

    return [
        {**perte, "at_boundary": True,
         "reason": "Perdu au bord d'un extrait : la coupe est trop serrée."}
        for perte in comparison["missing"]
        if perte["at_word"] in bords
    ]


def verification_report() -> Dict[str, Any]:
    """
    Ce que la vérification garantit, et ce qu'elle ne voit pas.

    Returns:
        Les verdicts, ce qui est hors de portée, et les règles tenues.
    """
    return {
        "verdicts": [CONFORME, DIVERGENT, NON_VERIFIE],
        "out_of_scope": dict(HORS_PORTEE),
        "rules": [
            "Un rendu terminé n'est **pas** un rendu vérifié : l'encodeur "
            "rapporte un succès pour un fichier dont une coupe a enlevé le mot "
            "« pas ».",
            "Une vérification qui n'a pas pu avoir lieu rend `NOT_VERIFIED`, "
            "jamais une réussite — sauter le contrôle puis annoncer « vérifié » "
            "fabrique de la confiance à partir d'une absence.",
            "La comparaison est **mécanique** : demander à un modèle si deux "
            "transcriptions se valent remplacerait une mesure par une opinion, "
            "produite par le même genre de système que l'erreur.",
            "La tolérance par défaut est 1.0 : un montage garde exactement ce "
            "qu'il a sélectionné, et tolérer une perte normaliserait la faute "
            "recherchée.",
            "Un mot perdu au bord d'un extrait est distingué d'un mot perdu au "
            "milieu : les deux ne se corrigent pas pareil.",
            "Ce qui n'est pas visible ici est **nommé** — une liste de "
            "contrôles qui ne montre que le détectable se lit comme complète.",
        ],
        "does_not": [
            "Déclarer conforme un rendu qui n'a pas été ré-écouté.",
            "Demander à un modèle de juger la conformité.",
            "Comparer à un texte attendu vide.",
            "Voir ce qu'une suite de mots ne porte pas : ton, débit, image.",
        ],
    }
